export const countries_english = {
  Shqipëria: 'Albania',
  Österreich: 'Austria',
  'Belgique/België': 'Belgium',
  'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
  Bulgaria: 'Bulgaria',
  'Schweiz/Suisse/Svizzera': 'Switzerland',
  Kosovo: 'Kosovo',
  Kýpros: 'Cyprus',
  Česko: 'Czech Republic',
  Deutschland: 'Germany',
  Danmark: 'Denmark',
  Eesti: 'Estonia',
  Elláda: 'Greece',
  España: 'Spain',
  'Suomi/Finland': 'Finland',
  France: 'France',
  Hrvatska: 'Croatia',
  Magyarország: 'Hungary',
  'Éire/Ireland': 'Ireland',
  Ísland: 'Iceland',
  Italia: 'Italy',
  Liechtenstein: 'Liechtenstein',
  Lietuva: 'Lithuania',
  Luxembourg: 'Luxembourg',
  Latvija: 'Latvia',
  'Crna Gora': 'Montenegro',
  'Severna Makedonija': 'North Macedonia',
  Malta: 'Malta',
  Moldova: 'Moldova',
  Nederland: 'Netherlands',
  Norge: 'Norway',
  Polska: 'Poland',
  Portugal: 'Portugal',
  România: 'Romania',
  Serbia: 'Serbia',
  Sverige: 'Sweden',
  Slovenija: 'Slovenia',
  Slovensko: 'Slovakia',
  Türkiye: 'Turkey',
  'United Kingdom': 'United Kingdom',
  Ukraine: 'Ukraine',
};
